# Generated by Django 5.2.12 on 2026-03-15 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zentinelle', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usagesummary',
            unique_together={('tenant_id', 'period', 'period_start', 'user_identifier', 'endpoint_id', 'deployment_id', 'ai_provider', 'ai_model')},
        ),
    ]
