# Generated by Django 5.2.12 on 2026-03-15 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zentinelle', '0002_fix_usagesummary_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='compliancealert',
            name='acknowledged_by',
            field=models.CharField(blank=True, default='', help_text='user_id who acknowledged', max_length=255),
        ),
        migrations.AddField(
            model_name='incident',
            name='reporter_id',
            field=models.CharField(blank=True, default='', help_text='Reported by (user_id)', max_length=255),
        ),
        migrations.AddField(
            model_name='organizationmodelapproval',
            name='reviewer_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='risk',
            name='reviewer_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='compliancealert',
            name='user_id',
            field=models.CharField(blank=True, db_index=True, default='', help_text='user_id who resolved (or last acted)', max_length=255),
        ),
        migrations.AlterField(
            model_name='incident',
            name='user_id',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Assigned to (user_id)', max_length=255),
        ),
    ]
