# Generated by Django 6.0.3 on 2026-03-15 16:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zentinelle", "0003_add_separate_user_role_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="policy",
            name="version",
            field=models.PositiveIntegerField(
                default=1, help_text="Current version number, incremented on each save"
            ),
        ),
        migrations.CreateModel(
            name="PolicyRevision",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("version", models.PositiveIntegerField()),
                ("name", models.CharField(max_length=255)),
                ("policy_type", models.CharField(max_length=50)),
                ("enforcement", models.CharField(max_length=20)),
                ("config", models.JSONField(default=dict)),
                ("scope_type", models.CharField(max_length=30)),
                ("enabled", models.BooleanField(default=True)),
                ("priority", models.IntegerField(default=0)),
                (
                    "changed_by",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("change_summary", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "policy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revisions",
                        to="zentinelle.policy",
                    ),
                ),
            ],
            options={
                "verbose_name": "Policy Revision",
                "verbose_name_plural": "Policy Revisions",
                "ordering": ["-version"],
                "unique_together": {("policy", "version")},
            },
        ),
    ]
