# Generated by Django 6.0.3 on 2026-03-15 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zentinelle", "0004_add_policy_version_history"),
    ]

    operations = [
        migrations.AddField(
            model_name="auditlog",
            name="entry_hash",
            field=models.CharField(
                blank=True,
                default="",
                help_text="SHA-256 of this record content",
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name="auditlog",
            name="chain_hash",
            field=models.CharField(
                blank=True,
                default="",
                help_text="SHA-256(prev_chain_hash + entry_hash) — links to previous record",
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name="auditlog",
            name="chain_sequence",
            field=models.BigIntegerField(
                db_index=True,
                default=0,
                help_text="Monotonically increasing per-tenant sequence number",
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["tenant_id", "chain_sequence"],
                name="zentinelle__tenant_i_chain_s_idx",
            ),
        ),
    ]
