# Generated by Django 5.2.12 on 2026-03-15 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zentinelle', '0008_report'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='zentinelle__tenant__2aff7c_idx',
            old_name='zentinelle__tenant_i_chain_s_idx',
        ),
        migrations.AlterField(
            model_name='incidentcomment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='notificationconfig',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='policy_type',
            field=models.CharField(choices=[('system_prompt', 'System Prompt'), ('ai_guardrail', 'AI Guardrail'), ('prompt_injection', 'Prompt Injection'), ('model_restriction', 'Model Restriction'), ('context_limit', 'Context Limit'), ('output_filter', 'Output Filter'), ('agent_capability', 'Agent Capability'), ('agent_memory', 'Agent Memory'), ('agent_delegation', 'Agent Delegation'), ('human_oversight', 'Human Oversight'), ('resource_quota', 'Resource Quota'), ('budget_limit', 'Budget Limit'), ('rate_limit', 'Rate Limit'), ('behavioral_baseline', 'Behavioral Baseline'), ('tool_permission', 'Tool Permission'), ('network_policy', 'Network Policy'), ('secret_access', 'Secret Access'), ('data_access', 'Data Access'), ('audit_policy', 'Audit Policy'), ('session_policy', 'Session Policy'), ('session_quota', 'Session Quota'), ('data_retention', 'Data Retention')], max_length=50),
        ),
        migrations.AlterField(
            model_name='report',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='report',
            name='report_type',
            field=models.CharField(choices=[('control_coverage', 'Control Coverage'), ('violation_summary', 'Violation Summary'), ('audit_trail', 'Audit Trail')], max_length=30),
        ),
    ]
