# Generated by Django 6.0.3 on 2026-03-16 00:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zentinelle", "0010_compliance_framework_config"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("tenant_id", models.CharField(db_index=True, max_length=255)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("policy_violation", "Policy Violation"),
                            ("budget_warning", "Budget Warning"),
                            ("high_risk", "High Risk Score"),
                            ("incident_opened", "Incident Opened"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                ("subject", models.CharField(max_length=255)),
                ("message", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[("UNREAD", "Unread"), ("READ", "Read")],
                        db_index=True,
                        default="UNREAD",
                        max_length=10,
                    ),
                ),
                ("status_date", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["tenant_id", "status", "-created_at"],
                        name="zentinelle__tenant__95c746_idx",
                    )
                ],
            },
        ),
    ]
