# Generated by Django 5.2.12 on 2026-03-16 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zentinelle', '0014_tenantconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemprompt',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Verified by Calliope AI team'),
        ),
    ]
