# Generated by Django 6.0.3 on 2026-03-16 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zentinelle", "0016_add_claude_code_gemini_codex_agent_types"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agentendpoint",
            name="agent_type",
            field=models.CharField(
                choices=[
                    ("claude_code", "Claude Code"),
                    ("gemini", "Gemini"),
                    ("codex", "Codex"),
                    ("junohub", "JunoHub"),
                    ("langchain", "LangChain"),
                    ("langgraph", "LangGraph"),
                    ("mcp", "MCP Server"),
                    ("chat", "Chat Agent"),
                    ("custom", "Custom"),
                ],
                default="custom",
                max_length=50,
            ),
        ),
    ]
