# Generated by Django 5.2.14 on 2026-05-06 15:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zentinelle", "0017_rename_jupyterhub_to_junohub"),
    ]

    operations = [
        migrations.CreateModel(
            name="BootstrapToken",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("tenant_id", models.CharField(db_index=True, max_length=255)),
                ("token_hash", models.CharField(max_length=128, unique=True)),
                ("token_prefix", models.CharField(max_length=16)),
                (
                    "label",
                    models.CharField(
                        blank=True, help_text="Human-readable label", max_length=255
                    ),
                ),
                ("revoked", models.BooleanField(default=False)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                ("use_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["tenant_id", "revoked"],
                        name="zentinelle__tenant__f40d39_idx",
                    )
                ],
            },
        ),
    ]
