# Generated by Django 5.2.14 on 2026-05-07 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zentinelle", "0019_add_safety_settings_policy_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="policy",
            name="policy_type",
            field=models.CharField(
                choices=[
                    ("system_prompt", "System Prompt"),
                    ("ai_guardrail", "AI Guardrail"),
                    ("prompt_injection", "Prompt Injection"),
                    ("model_restriction", "Model Restriction"),
                    ("context_limit", "Context Limit"),
                    ("output_filter", "Output Filter"),
                    ("agent_capability", "Agent Capability"),
                    ("agent_memory", "Agent Memory"),
                    ("agent_delegation", "Agent Delegation"),
                    ("human_oversight", "Human Oversight"),
                    ("resource_quota", "Resource Quota"),
                    ("budget_limit", "Budget Limit"),
                    ("rate_limit", "Rate Limit"),
                    ("behavioral_baseline", "Behavioral Baseline"),
                    ("tool_permission", "Tool Permission"),
                    ("network_policy", "Network Policy"),
                    ("secret_access", "Secret Access"),
                    ("data_access", "Data Access"),
                    ("audit_policy", "Audit Policy"),
                    ("session_policy", "Session Policy"),
                    ("session_quota", "Session Quota"),
                    ("data_retention", "Data Retention"),
                    ("safety_settings", "Safety Settings (Gemini)"),
                    ("multimodal_policy", "Multimodal Content Policy"),
                ],
                max_length=50,
            ),
        ),
    ]
