# Generated by Django 5.2.14 on 2026-05-07 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zentinelle", "0020_add_multimodal_policy_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agentendpoint",
            name="agent_id",
            field=models.SlugField(
                help_text="Unique identifier for this agent within a tenant (e.g., junohub-prod-west-2)",
                max_length=100,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="agentendpoint",
            unique_together={("tenant_id", "agent_id")},
        ),
    ]
