# Generated by Django 5.2.14 on 2026-05-07 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zentinelle", "0021_alter_agentendpoint_agent_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bootstraptoken",
            name="max_uses",
            field=models.PositiveIntegerField(default=0, help_text="0 = unlimited"),
        ),
        migrations.AddField(
            model_name="bootstraptoken",
            name="single_use",
            field=models.BooleanField(
                default=False, help_text="Revoke after first use"
            ),
        ),
    ]
