# Generated by Django 5.2.14 on 2026-05-08 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zentinelle", "0022_bootstrap_token_single_use"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agentendpoint",
            name="agent_type",
            field=models.CharField(
                choices=[
                    ("claude_code", "Claude Code"),
                    ("gemini", "Gemini"),
                    ("codex", "Codex"),
                    ("calliope", "Calliope AI"),
                    ("langchain", "LangChain"),
                    ("langgraph", "LangGraph"),
                    ("mcp", "MCP Server"),
                    ("chat", "Chat Agent"),
                    ("custom", "Custom"),
                ],
                default="custom",
                max_length=50,
            ),
        ),
    ]
