# Generated by Django 5.2.14 on 2026-05-08 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zentinelle", "0023_rename_junohub_to_calliope"),
    ]

    operations = [
        migrations.AddField(
            model_name="risk",
            name="severity",
            field=models.IntegerField(
                choices=[
                    (1, "Minimal (1)"),
                    (2, "Low (2)"),
                    (3, "Moderate (3)"),
                    (5, "High (5)"),
                    (8, "Critical (8)"),
                ],
                default=3,
            ),
        ),
        migrations.AlterField(
            model_name="risk",
            name="impact",
            field=models.IntegerField(
                choices=[
                    (1, "Negligible (1)"),
                    (2, "Minor (2)"),
                    (3, "Moderate (3)"),
                    (5, "Major (5)"),
                    (8, "Severe (8)"),
                ],
                default=3,
            ),
        ),
        migrations.AlterField(
            model_name="risk",
            name="likelihood",
            field=models.IntegerField(
                choices=[
                    (1, "Rare (1)"),
                    (2, "Unlikely (2)"),
                    (3, "Possible (3)"),
                    (5, "Likely (5)"),
                    (8, "Almost Certain (8)"),
                ],
                default=3,
            ),
        ),
        migrations.AlterField(
            model_name="risk",
            name="residual_impact",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "Negligible (1)"),
                    (2, "Minor (2)"),
                    (3, "Moderate (3)"),
                    (5, "Major (5)"),
                    (8, "Severe (8)"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="risk",
            name="residual_likelihood",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "Rare (1)"),
                    (2, "Unlikely (2)"),
                    (3, "Possible (3)"),
                    (5, "Likely (5)"),
                    (8, "Almost Certain (8)"),
                ],
                null=True,
            ),
        ),
    ]
