# Generated by Django 5.2.14 on 2026-05-08 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zentinelle", "0024_add_severity_fmea"),
    ]

    operations = [
        migrations.CreateModel(
            name="LLMProviderKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tenant_id", models.CharField(db_index=True, max_length=255)),
                ("provider", models.CharField(db_index=True, max_length=50)),
                ("encrypted_key", models.BinaryField()),
                ("key_prefix", models.CharField(default="", max_length=20)),
                ("is_active", models.BooleanField(default=True)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "zentinelle_llm_provider_key",
                "unique_together": {("tenant_id", "provider")},
            },
        ),
    ]
