# Generated by Django 5.2.14 on 2026-05-08 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zentinelle", "0025_add_llm_provider_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="llmproviderkey",
            name="enabled_for_assistant",
            field=models.BooleanField(
                default=True,
                help_text="Whether to expose this provider's models in the AI assistant. Models are still discovered for the registry regardless.",
            ),
        ),
        migrations.AlterField(
            model_name="llmproviderkey",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Whether the key is configured (set to False on revoke)",
            ),
        ),
    ]
