# Generated by Django 5.2.14 on 2026-05-08 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zentinelle', '0026_add_assistant_toggle'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimodel',
            name='enabled_for_chat',
            field=models.BooleanField(default=True, help_text='User-controlled: include this model in the assistant chat picker.'),
        ),
    ]
