# Generated by Django 5.2.15 on 2026-08-31 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zentinelle', '0027_add_enabled_for_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='apikey',
            name='key_type',
            field=models.CharField(choices=[('user', 'User'), ('service', 'Service')], db_index=True, default='user', help_text="user = a person's platform key; service = a platform-level integration such as Astrolift calling on behalf of a tenant", max_length=20),
        ),
    ]
