# Generated by Django 5.2.15 on 2026-08-31 05:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zentinelle', '0028_service_api_key_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='AstroliftIntegration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.CharField(db_index=True, max_length=255)),
                ('astrolift_org_id', models.BigIntegerField(db_index=True, unique=True)),
                ('astrolift_url', models.URLField(blank=True, max_length=500)),
                ('signing_secret', models.CharField(help_text='Shared secret for the X-Astrolift-Signature HMAC', max_length=500)),
                ('previous_signing_secret', models.CharField(blank=True, default='', help_text='Accepted alongside signing_secret so a secret can be rotated without dropping in-flight deliveries. Clear it once rotation has settled.', max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('last_event_at', models.DateTimeField(blank=True, null=True)),
                ('events_accepted', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Astrolift Integration',
            },
        ),
        migrations.CreateModel(
            name='AstroliftAuditDelivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('idempotency_key', models.CharField(db_index=True, max_length=255, unique=True)),
                ('tenant_id', models.CharField(db_index=True, max_length=255)),
                ('astrolift_event_id', models.CharField(db_index=True, max_length=255)),
                ('event_type', models.CharField(max_length=100)),
                ('audit_log_id', models.UUIDField(blank=True, null=True)),
                ('received_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Astrolift Audit Delivery',
                'verbose_name_plural': 'Astrolift Audit Deliveries',
                'indexes': [models.Index(fields=['tenant_id', 'received_at'], name='zentinelle__tenant__3a4064_idx')],
            },
        ),
    ]
