# Generated by Django 5.2.15 on 2026-08-31 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zentinelle", "0029_astrolift_integration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agentendpoint",
            name="agent_type",
            field=models.CharField(
                choices=[
                    ("claude_code", "Claude Code"),
                    ("gemini", "Gemini"),
                    ("antigravity", "Antigravity CLI"),
                    ("opencode", "OpenCode"),
                    ("codex", "Codex"),
                    ("calliope", "Calliope AI"),
                    ("langchain", "LangChain"),
                    ("langgraph", "LangGraph"),
                    ("mcp", "MCP Server"),
                    ("chat", "Chat Agent"),
                    ("custom", "Custom"),
                ],
                default="custom",
                max_length=50,
            ),
        ),
    ]
