# Generated by Django 5.2.15 on 2026-08-31 06:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zentinelle", "0030_alter_agentendpoint_agent_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="timestamp",
            field=models.DateTimeField(
                db_index=True, default=django.utils.timezone.now
            ),
        ),
        migrations.AddConstraint(
            model_name="auditlog",
            constraint=models.UniqueConstraint(
                condition=models.Q(("chain_sequence__gt", 0)),
                fields=("tenant_id", "chain_sequence"),
                name="unique_audit_chain_sequence_per_tenant",
            ),
        ),
    ]
