# Generated by Django 5.2.15 on 2026-08-31 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zentinelle", "0031_alter_auditlog_timestamp_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditChainHead",
            fields=[
                (
                    "tenant_id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("last_sequence", models.BigIntegerField(default=0)),
                (
                    "last_chain_hash",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "audit chain head",
                "verbose_name_plural": "audit chain heads",
            },
        ),
    ]
