# Generated by Django 5.2.14 on 2026-08-31 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zentinelle", "0032_auditchainhead"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agentendpoint",
            name="agent_type",
            field=models.CharField(
                choices=[
                    ("claude_code", "Claude Code"),
                    ("gemini", "Gemini"),
                    ("antigravity", "Antigravity CLI"),
                    ("opencode", "OpenCode"),
                    ("codex", "Codex"),
                    ("calliope", "Calliope AI"),
                    ("langchain", "LangChain"),
                    ("langgraph", "LangGraph"),
                    ("crewai", "CrewAI"),
                    ("llamaindex", "LlamaIndex"),
                    ("ms-agent-framework", "Microsoft Agent Framework"),
                    ("openai_agents", "OpenAI Agents SDK"),
                    ("vercel-ai", "Vercel AI SDK"),
                    ("mcp", "MCP Server"),
                    ("chat", "Chat Agent"),
                    ("custom", "Custom"),
                ],
                default="custom",
                max_length=50,
            ),
        ),
    ]
