# Generated by Django 5.2.14 on 2026-08-31 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zentinelle", "0035_add_tier3_harness_agent_types"),
    ]

    operations = [
        migrations.AddField(
            model_name="usagemetric",
            name="billing_exported_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="When this metric was exported to Calliope AI billing",
                null=True,
            ),
        ),
        migrations.AddIndex(
            model_name="usagemetric",
            index=models.Index(
                fields=["billing_exported_at", "metric_type", "occurred_at"],
                name="zentinelle__billing_a28d52_idx",
            ),
        ),
    ]
