# Generated by Django 5.2.14 on 2026-09-11 04:36

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zentinelle", "0036_add_billing_export_marker"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExecutionApproval",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("tenant_id", models.CharField(db_index=True, max_length=255)),
                ("kind", models.CharField(max_length=20)),
                ("endpoint_id_ext", models.CharField(blank=True, max_length=255)),
                ("subject", models.CharField(blank=True, max_length=255)),
                ("action", models.CharField(max_length=255)),
                ("context_digest", models.CharField(max_length=64)),
                ("policy_versions", models.JSONField(default=dict)),
                ("granted_by", models.CharField(blank=True, max_length=255)),
                ("expires_at", models.DateTimeField(db_index=True)),
                ("consumed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name="agentendpoint",
            name="sub_organization_id_ext",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="policy",
            name="non_overridable",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="policy",
            name="override_group",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
