# Generated by Django 5.2.14 on 2026-09-11 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zentinelle", "0037_dependable_approvals_and_policy_scopes"),
    ]

    operations = [
        migrations.AddField(
            model_name="auditchainhead",
            name="archived_chain_hash",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="auditchainhead",
            name="archived_checkpoint",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="auditchainhead",
            name="archived_sequence",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="auditlog",
            name="hash_version",
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="auditlog", name="hash_version",
            field=models.PositiveSmallIntegerField(default=2),
        ),
        migrations.CreateModel(
            name="AuditRetentionProof",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tenant_id", models.CharField(db_index=True, max_length=255)),
                ("first_sequence", models.BigIntegerField()),
                ("last_sequence", models.BigIntegerField()),
                ("proof", models.TextField()),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant_id", "first_sequence"),
                        name="unique_audit_retention_proof",
                    )
                ],
            },
        ),
    ]
