# Generated by Django 5.2.14 on 2026-09-11 04:42

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zentinelle", "0038_verifiable_audit_retention"),
    ]

    operations = [
        migrations.CreateModel(
            name="BudgetAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tenant_id", models.CharField(db_index=True, max_length=255)),
                ("policy_id_ext", models.UUIDField()),
                ("period", models.DateField()),
                (
                    "committed_usd",
                    models.DecimalField(decimal_places=8, default=0, max_digits=20),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant_id", "policy_id_ext", "period"),
                        name="unique_budget_account",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="BudgetCharge",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("tenant_id", models.CharField(db_index=True, max_length=255)),
                ("endpoint_id_ext", models.UUIDField()),
                ("request_id", models.CharField(max_length=255)),
                ("amount_usd", models.DecimalField(decimal_places=8, max_digits=20)),
                ("account_ids", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant_id", "endpoint_id_ext", "request_id"),
                        name="unique_budget_request",
                    )
                ],
            },
        ),
    ]
