# Generated by Django 5.2.17 on 2026-09-11 06:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zentinelle", "0039_atomic_budget_admission"),
    ]

    operations = [
        migrations.CreateModel(
            name="PolicyChangeSet",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("tenant_id", models.CharField(db_index=True, max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("validated", "Validated"),
                            ("staged", "Staged"),
                            ("approved", "Approved"),
                            ("promoted", "Promoted"),
                            ("rolled_back", "Rolled Back"),
                            ("rejected", "Rejected"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                ("changes", models.JSONField(default=list)),
                ("base_versions", models.JSONField(default=dict)),
                ("validation", models.JSONField(default=dict)),
                ("target_selectors", models.JSONField(default=dict)),
                ("created_by", models.CharField(default="system", max_length=255)),
                (
                    "reviewed_by",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "approved_by",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("staged_at", models.DateTimeField(blank=True, null=True)),
                ("promoted_at", models.DateTimeField(blank=True, null=True)),
                ("rolled_back_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["tenant_id", "status", "-created_at"],
                        name="zentinelle__tenant__b2ebde_idx",
                    )
                ],
            },
        ),
    ]
