# Generated by Django 5.2.17 on 2026-09-11 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zentinelle", "0040_policychangeset"),
    ]

    operations = [
        migrations.AddField(
            model_name="policychangeset",
            name="applied_snapshots",
            field=models.JSONField(default=list),
        ),
    ]
