# Generated by Django 5.2.17 on 2026-09-11 06:28

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zentinelle", "0041_policychangeset_applied_snapshots"),
    ]

    operations = [
        migrations.CreateModel(
            name="PolicyChangeAcknowledgement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("tenant_id", models.CharField(db_index=True, max_length=255)),
                ("subject_type", models.CharField(max_length=30)),
                ("subject_id", models.CharField(max_length=255)),
                ("policy_version", models.JSONField(default=dict)),
                ("acknowledgement_digest", models.CharField(max_length=128)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("acknowledged", "Acknowledged"),
                            ("rejected", "Rejected"),
                        ],
                        max_length=20,
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("acknowledged_at", models.DateTimeField(auto_now_add=True)),
                (
                    "change_set",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="acknowledgements",
                        to="zentinelle.policychangeset",
                    ),
                ),
            ],
            options={
                "ordering": ["-acknowledged_at"],
                "indexes": [
                    models.Index(
                        fields=["tenant_id", "change_set", "status"],
                        name="zentinelle__tenant__c912c4_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("change_set", "subject_type", "subject_id"),
                        name="unique_policy_change_ack_subject",
                    )
                ],
            },
        ),
    ]
