# Generated by Django 5.2.17 on 2026-09-11 06:32

import uuid

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zentinelle", "0042_policychangeacknowledgement"),
    ]

    operations = [
        migrations.CreateModel(
            name="ControlEvidence",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("tenant_id", models.CharField(db_index=True, max_length=255)),
                ("control_id", models.CharField(db_index=True, max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("verified-operating", "Verified Operating"),
                            ("stale", "Stale"),
                            ("failed", "Failed"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=30,
                    ),
                ),
                ("owner", models.CharField(blank=True, default="", max_length=255)),
                ("scope", models.JSONField(blank=True, default=dict)),
                ("evidence_links", models.JSONField(blank=True, default=list)),
                ("test_results", models.JSONField(blank=True, default=dict)),
                (
                    "captured_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("source", models.CharField(blank=True, default="", max_length=255)),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-captured_at"],
                "indexes": [
                    models.Index(
                        fields=["tenant_id", "control_id", "-captured_at"],
                        name="zentinelle__tenant__369981_idx",
                    )
                ],
            },
        ),
    ]
