# Generated by Django 5.2.17 on 2026-09-11 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zentinelle", "0043_controlevidence"),
    ]

    operations = [
        migrations.AddField(
            model_name="budgetcharge",
            name="actual_usd",
            field=models.DecimalField(
                blank=True, decimal_places=8, max_digits=20, null=True
            ),
        ),
        migrations.AddField(
            model_name="budgetcharge",
            name="reconciled_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="budgetcharge",
            name="reconciliation_source",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
    ]
