# Generated by Django 5.2.17 on 2026-09-11 06:45

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "zentinelle",
            "0044_budgetcharge_actual_usd_budgetcharge_reconciled_at_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="RetentionOutcome",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("tenant_id", models.CharField(db_index=True, max_length=255)),
                ("entity_type", models.CharField(max_length=40)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("preserved_for_review", "Preserved for review"),
                            ("archived", "Archived"),
                            ("deleted", "Deleted"),
                            ("failed", "Failed"),
                            ("held", "Held"),
                        ],
                        max_length=30,
                    ),
                ),
                ("record_count", models.PositiveIntegerField(default=0)),
                ("manifest", models.JSONField(blank=True, default=dict)),
                (
                    "manifest_digest",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                (
                    "destination",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                ("error", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["tenant_id", "entity_type", "-created_at"],
                        name="zentinelle__tenant__0f9037_idx",
                    )
                ],
            },
        ),
    ]
