# Generated by Django 5.2.17 on 2026-09-11 06:48

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zentinelle", "0046_eventdeliveryoutbox"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReleaseQualification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("release_id", models.CharField(max_length=255, unique=True)),
                ("version", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[("qualified", "Qualified"), ("rejected", "Rejected")],
                        max_length=20,
                    ),
                ),
                ("checks", models.JSONField(default=dict)),
                ("rollback_evidence", models.JSONField(blank=True, default=dict)),
                (
                    "sbom_digest",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                ("signature", models.TextField(blank=True, default="")),
                (
                    "qualified_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
        ),
    ]
