# Generated by Django 5.2.17 on 2026-09-11 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zentinelle", "0047_releasequalification"),
    ]

    operations = [
        migrations.AddField(
            model_name="budgetcharge",
            name="pricing_version",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
    ]
