# Generated by Django 5.2.17 on 2026-09-11 08:09

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zentinelle", "0049_runtimesettingsrevision"),
    ]

    operations = [
        migrations.CreateModel(
            name="RuntimeSettingsChange",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("tenant_id", models.CharField(db_index=True, max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("staged", "Staged"),
                            ("approved", "Approved"),
                            ("applied", "Applied"),
                            ("rejected", "Rejected"),
                            ("rolled_back", "Rolled Back"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("settings", models.JSONField(default=dict)),
                ("base_revision", models.PositiveIntegerField(default=0)),
                ("created_by", models.CharField(default="system", max_length=255)),
                (
                    "approved_by",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "applied_revision",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("applied_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["tenant_id", "status", "-created_at"],
                        name="zentinelle__tenant__b3ff3c_idx",
                    )
                ],
            },
        ),
    ]
