# Generated by Django 5.2.17 on 2026-09-11 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zentinelle", "0050_runtimesettingschange"),
    ]

    operations = [
        migrations.AddField(
            model_name="budgetcharge",
            name="app_id_ext",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="budgetcharge",
            name="session_id_ext",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="budgetcharge",
            name="task_id_ext",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="budgetcharge",
            name="team_id_ext",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=255
            ),
        ),
    ]
