# Generated by Django 5.2.17 on 2026-09-13 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zentinelle", "0056_complete_partial_schema_repair"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="producer_event_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Producer-assigned event ID used for idempotent ingestion",
                max_length=255,
            ),
        ),
        migrations.AddConstraint(
            model_name="event",
            constraint=models.UniqueConstraint(
                condition=models.Q(("producer_event_id", ""), _negated=True),
                fields=("tenant_id", "endpoint", "producer_event_id"),
                name="event_producer_id_per_endpoint",
            ),
        ),
    ]
