# Generated by Django 5.2.17 on 2026-09-23 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zentinelle", "0057_event_producer_idempotency"),
    ]

    operations = [
        migrations.AddField(
            model_name="agentendpoint",
            name="api_key_expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
