# Generated by Django 5.2.15 on 2026-09-23 02:07

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zentinelle", "0058_agentendpoint_api_key_expires_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agentendpoint",
            name="agent_type",
            field=models.CharField(
                choices=[
                    ("claude_code", "Claude Code"),
                    ("gemini", "Gemini"),
                    ("antigravity", "Antigravity CLI"),
                    ("opencode", "OpenCode"),
                    ("codex", "Codex"),
                    ("calliope", "Calliope AI"),
                    ("langchain", "LangChain"),
                    ("langgraph", "LangGraph"),
                    ("crewai", "CrewAI"),
                    ("llamaindex", "LlamaIndex"),
                    ("ms-agent-framework", "Microsoft Agent Framework"),
                    ("openai_agents", "OpenAI Agents SDK"),
                    ("agno", "Agno"),
                    ("google_adk", "Google ADK"),
                    ("haystack", "Haystack"),
                    ("letta", "Letta"),
                    ("pydantic_ai", "Pydantic AI"),
                    ("smolagents", "Smolagents"),
                    ("bee_agent", "BeeAI Framework"),
                    ("dspy", "DSPy"),
                    ("mistral_agents", "Mistral Agents"),
                    ("spring_ai", "Spring AI"),
                    ("vercel-ai", "Vercel AI SDK"),
                    ("mcp", "MCP Server"),
                    ("agent_host", "Agent Host"),
                    ("chat", "Chat Agent"),
                    ("custom", "Custom"),
                ],
                default="custom",
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="ApprovalRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("tenant_id", models.CharField(db_index=True, max_length=255)),
                ("endpoint_id_ext", models.CharField(max_length=255)),
                ("subject", models.CharField(blank=True, max_length=255)),
                ("action", models.CharField(max_length=255)),
                ("context_digest", models.CharField(max_length=64)),
                ("context", models.JSONField(blank=True, default=dict)),
                ("reason", models.TextField(blank=True)),
                ("trace_id", models.CharField(blank=True, max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("denied", "Denied"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("expires_at", models.DateTimeField()),
                ("decided_by", models.CharField(blank=True, max_length=255)),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                ("decision_reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "approval",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="request",
                        to="zentinelle.executionapproval",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["tenant_id", "status", "expires_at"],
                        name="zentinelle__tenant__ae3891_idx",
                    )
                ],
            },
        ),
    ]
