# Generated by Django 5.2.17 on 2026-09-23 12:56

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zentinelle", "0059_agent_host_approval_request"),
    ]

    operations = [
        migrations.CreateModel(
            name="GatewayRegistration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                (
                    "cluster_id",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=255
                    ),
                ),
                (
                    "tenant_ids",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Tenants this gateway may read stored provider keys for. Empty serves none.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "revoked_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Set to revoke the gateway: every credential it holds stops working.",
                        null=True,
                    ),
                ),
            ],
            options={
                "db_table": "zentinelle_gateway_registration",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="GatewayCredential",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("key_prefix", models.CharField(db_index=True, max_length=24)),
                ("key_hash", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "registration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="credentials",
                        to="zentinelle.gatewayregistration",
                    ),
                ),
            ],
            options={
                "db_table": "zentinelle_gateway_credential",
                "ordering": ["-created_at"],
            },
        ),
    ]
