# Generated by Django 5.2.17 on 2026-09-23 14:11

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zentinelle", "0060_gateway_registration_credential"),
    ]

    operations = [
        migrations.CreateModel(
            name="AstroliftCluster",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("external_id", models.CharField(max_length=128)),
                ("provider", models.CharField(blank=True, default="", max_length=50)),
                ("region", models.CharField(blank=True, default="", max_length=100)),
                (
                    "health",
                    models.CharField(
                        choices=[
                            ("unknown", "Unknown"),
                            ("healthy", "Healthy"),
                            ("degraded", "Degraded"),
                            ("unhealthy", "Unhealthy"),
                        ],
                        default="unknown",
                        max_length=20,
                    ),
                ),
                ("last_seen_at", models.DateTimeField(blank=True, null=True)),
                (
                    "gateway_version",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "counters",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="The counters of the latest heartbeat.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "zentinelle_astrolift_cluster",
                "ordering": ["external_id", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AstroliftInstall",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("base_url", models.URLField(max_length=500)),
                (
                    "tenant_ids",
                    models.JSONField(
                        default=list,
                        help_text="Tenants this install may serve, from its enrollment code.",
                    ),
                ),
                ("key_prefix", models.CharField(db_index=True, max_length=24)),
                ("key_hash", models.CharField(max_length=255)),
                ("connected_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "zentinelle_astrolift_install",
                "ordering": ["-connected_at"],
            },
        ),
        migrations.CreateModel(
            name="EnrollmentCode",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code_hash", models.CharField(max_length=64, unique=True)),
                (
                    "tenant_ids",
                    models.JSONField(
                        default=list,
                        help_text="Tenants the install that uses this code may serve.",
                    ),
                ),
                (
                    "created_by",
                    models.CharField(
                        help_text="Who generated it: a portal username or manage.py.",
                        max_length=255,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("used_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "zentinelle_astrolift_enrollment_code",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="gatewaycredential",
            name="expires_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When set, the credential stops working at this time.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="gatewayregistration",
            name="astrolift_cluster",
            field=models.ForeignKey(
                blank=True,
                help_text="The Astrolift cluster this gateway runs in, when an Astrolift install registered it.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="gateway_registrations",
                to="zentinelle.astroliftcluster",
            ),
        ),
        migrations.AddField(
            model_name="astroliftcluster",
            name="install",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="clusters",
                to="zentinelle.astroliftinstall",
            ),
        ),
        migrations.AddField(
            model_name="astroliftinstall",
            name="enrollment_code",
            field=models.OneToOneField(
                help_text="The code this install consumed. One-to-one: a code connects one install.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="install",
                to="zentinelle.enrollmentcode",
            ),
        ),
        migrations.AddConstraint(
            model_name="astroliftcluster",
            constraint=models.UniqueConstraint(
                condition=models.Q(("revoked_at__isnull", True)),
                fields=("install", "external_id"),
                name="unique_live_astrolift_cluster_per_install",
            ),
        ),
    ]
