# Generated by Django 5.2.17 on 2026-09-30 01:31

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zentinelle", "0064_agentendpoint_api_key_issued_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AstroliftEnforcement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("tenant_id", models.CharField(db_index=True, max_length=255)),
                ("evidence_id", models.CharField(max_length=255)),
                ("payload", models.JSONField(default=dict)),
                ("status", models.CharField(default="pending", max_length=20)),
                ("outcome", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("applied_at", models.DateTimeField(blank=True, null=True)),
                (
                    "endpoint",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="zentinelle.agentendpoint",
                    ),
                ),
                (
                    "install",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="zentinelle.astroliftinstall",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant_id", "install", "evidence_id"),
                        name="unique_astrolift_enforcement_evidence",
                    )
                ],
            },
        ),
    ]
