'use client';

import {
  Box,
  VStack,
  HStack,
  Text,
  Badge,
  Icon,
  Button,
  Select,
  Table,
  Thead,
  Tbody,
  Tr,
  Th,
  Td,
  Divider,
  useColorModeValue,
  useToast,
} from '@chakra-ui/react';
import { useState } from 'react';
import {
  MdDescription,
  MdDownload,
  MdCalendarToday,
  MdShield,
  MdCheckCircle,
  MdWarning,
  MdContentCopy,
  MdRefresh,
} from 'react-icons/md';

interface FrameworkSummary {
  id: string;
  name: string;
  score: number;
  requiredCovered: number;
  requiredTotal: number;
  gapCount: number;
}

interface ComplianceReportProps {
  organizationName: string;
  generatedAt?: string;
  overallScore: number;
  frameworks: FrameworkSummary[];
  onGenerateReport?: (format: 'pdf' | 'csv' | 'json') => void;
  onScheduleReport?: () => void;
}

function getScoreColor(score: number): string {
  if (score >= 80) return 'green';
  if (score >= 60) return 'yellow';
  if (score >= 40) return 'orange';
  return 'red';
}

function getStatusLabel(score: number): string {
  if (score >= 90) return 'Excellent';
  if (score >= 80) return 'Good';
  if (score >= 60) return 'Fair';
  if (score >= 40) return 'Needs Attention';
  return 'Critical';
}

export default function ComplianceReport({
  organizationName,
  generatedAt,
  overallScore,
  frameworks,
  onGenerateReport,
  onScheduleReport,
}: ComplianceReportProps) {
  const cardBg = useColorModeValue('white', 'navy.800');
  const borderColor = useColorModeValue('gray.200', 'whiteAlpha.200');
  const textColor = useColorModeValue('secondaryGray.900', 'white');
  const previewBg = useColorModeValue('gray.50', 'whiteAlpha.50');
  const toast = useToast();

  const [selectedFormat, setSelectedFormat] = useState<'pdf' | 'csv' | 'json'>('pdf');
  const [selectedPeriod, setSelectedPeriod] = useState('current');

  const reportDate = generatedAt ? new Date(generatedAt) : new Date();
  const scoreColor = getScoreColor(overallScore);

  // Calculate totals
  const totalGaps = frameworks.reduce((sum, f) => sum + f.gapCount, 0);
  const totalControls = frameworks.reduce((sum, f) => sum + f.requiredTotal, 0);
  const totalPassed = frameworks.reduce((sum, f) => sum + f.requiredCovered, 0);

  const handleCopyReport = () => {
    const reportText = generatePlainTextReport();
    navigator.clipboard.writeText(reportText);
    toast({
      title: 'Report copied to clipboard',
      status: 'success',
      duration: 2000,
    });
  };

  const generatePlainTextReport = () => {
    const lines = [
      `COMPLIANCE ASSESSMENT REPORT`,
      `Organization: ${organizationName}`,
      `Generated: ${reportDate.toLocaleDateString()} ${reportDate.toLocaleTimeString()}`,
      ``,
      `EXECUTIVE SUMMARY`,
      `Overall Compliance Score: ${Math.round(overallScore)}% (${getStatusLabel(overallScore)})`,
      `Total Controls: ${totalControls}`,
      `Controls Passed: ${totalPassed}`,
      `Open Gaps: ${totalGaps}`,
      ``,
      `FRAMEWORK BREAKDOWN`,
      ...frameworks.map(
        (f) =>
          `- ${f.name}: ${Math.round(f.score)}% (${f.requiredCovered}/${f.requiredTotal} required, ${f.gapCount} gaps)`
      ),
      ``,
      `---`,
      `Report generated by Zentinelle AI Governance Platform`,
    ];
    return lines.join('\n');
  };

  const handleExport = () => {
    if (onGenerateReport) {
      onGenerateReport(selectedFormat);
    } else {
      // Fallback: download as text for demo
      const content = generatePlainTextReport();
      const blob = new Blob([content], { type: 'text/plain' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `compliance-report-${reportDate.toISOString().split('T')[0]}.txt`;
      a.click();
      URL.revokeObjectURL(url);
      toast({
        title: 'Report downloaded',
        description: 'PDF export coming in next release',
        status: 'info',
        duration: 3000,
      });
    }
  };

  return (
    <Box>
      {/* Report Options */}
      <HStack
        spacing="16px"
        p="16px"
        bg={cardBg}
        borderRadius="lg"
        border="1px solid"
        borderColor={borderColor}
        mb="16px"
        flexWrap="wrap"
      >
        <HStack spacing="8px">
          <Icon as={MdCalendarToday} color="gray.500" />
          <Select
            size="sm"
            value={selectedPeriod}
            onChange={(e) => setSelectedPeriod(e.target.value)}
            maxW="150px"
          >
            <option value="current">Current Status</option>
            <option value="weekly">Weekly Summary</option>
            <option value="monthly">Monthly Summary</option>
            <option value="quarterly">Quarterly Review</option>
          </Select>
        </HStack>
        <HStack spacing="8px">
          <Icon as={MdDownload} color="gray.500" />
          <Select
            size="sm"
            value={selectedFormat}
            onChange={(e) => setSelectedFormat(e.target.value as 'pdf' | 'csv' | 'json')}
            maxW="120px"
          >
            <option value="pdf">PDF</option>
            <option value="csv">CSV</option>
            <option value="json">JSON</option>
          </Select>
        </HStack>
        <Button
          size="sm"
          colorScheme="brand"
          leftIcon={<MdDownload />}
          onClick={handleExport}
        >
          Export Report
        </Button>
        <Button
          size="sm"
          variant="outline"
          leftIcon={<MdContentCopy />}
          onClick={handleCopyReport}
        >
          Copy
        </Button>
        {onScheduleReport && (
          <Button
            size="sm"
            variant="ghost"
            leftIcon={<MdRefresh />}
            onClick={onScheduleReport}
          >
            Schedule
          </Button>
        )}
      </HStack>

      {/* Report Preview */}
      <Box
        p="24px"
        bg={cardBg}
        borderRadius="lg"
        border="1px solid"
        borderColor={borderColor}
      >
        {/* Header */}
        <VStack align="center" spacing="8px" mb="24px">
          <Icon as={MdDescription} boxSize="40px" color="brand.500" />
          <Text fontSize="xl" fontWeight="700" color={textColor}>
            Compliance Assessment Report
          </Text>
          <Text fontSize="sm" color="gray.500">
            {organizationName}
          </Text>
          <Text fontSize="xs" color="gray.400">
            Generated: {reportDate.toLocaleDateString()} at {reportDate.toLocaleTimeString()}
          </Text>
        </VStack>

        <Divider mb="24px" />

        {/* Executive Summary */}
        <Box mb="24px">
          <Text fontSize="md" fontWeight="600" color={textColor} mb="16px">
            Executive Summary
          </Text>
          <Box p="20px" bg={previewBg} borderRadius="md">
            <HStack spacing="32px" justify="center" flexWrap="wrap">
              <VStack>
                <Text fontSize="4xl" fontWeight="700" color={`${scoreColor}.500`}>
                  {Math.round(overallScore)}%
                </Text>
                <Badge colorScheme={scoreColor} fontSize="sm">
                  {getStatusLabel(overallScore)}
                </Badge>
                <Text fontSize="xs" color="gray.500">
                  Overall Score
                </Text>
              </VStack>
              <Divider orientation="vertical" h="80px" />
              <VStack>
                <Text fontSize="3xl" fontWeight="700" color={textColor}>
                  {frameworks.length}
                </Text>
                <Text fontSize="xs" color="gray.500">
                  Frameworks
                </Text>
              </VStack>
              <VStack>
                <Text fontSize="3xl" fontWeight="700" color="green.500">
                  {totalPassed}
                </Text>
                <Text fontSize="xs" color="gray.500">
                  Controls Passed
                </Text>
              </VStack>
              <VStack>
                <Text fontSize="3xl" fontWeight="700" color="orange.500">
                  {totalGaps}
                </Text>
                <Text fontSize="xs" color="gray.500">
                  Open Gaps
                </Text>
              </VStack>
            </HStack>
          </Box>
        </Box>

        {/* Framework Breakdown */}
        <Box mb="24px">
          <Text fontSize="md" fontWeight="600" color={textColor} mb="16px">
            Framework Breakdown
          </Text>
          <Table size="sm">
            <Thead>
              <Tr>
                <Th borderColor={borderColor}>Framework</Th>
                <Th borderColor={borderColor} isNumeric>
                  Score
                </Th>
                <Th borderColor={borderColor} isNumeric>
                  Required
                </Th>
                <Th borderColor={borderColor} isNumeric>
                  Passed
                </Th>
                <Th borderColor={borderColor} isNumeric>
                  Gaps
                </Th>
                <Th borderColor={borderColor}>Status</Th>
              </Tr>
            </Thead>
            <Tbody>
              {frameworks.map((fw) => {
                const fwScoreColor = getScoreColor(fw.score);
                return (
                  <Tr key={fw.id}>
                    <Td borderColor={borderColor}>
                      <HStack spacing="8px">
                        <Icon as={MdShield} color={`${fwScoreColor}.500`} />
                        <Text fontWeight="500">{fw.name}</Text>
                      </HStack>
                    </Td>
                    <Td borderColor={borderColor} isNumeric>
                      <Badge colorScheme={fwScoreColor}>
                        {Math.round(fw.score)}%
                      </Badge>
                    </Td>
                    <Td borderColor={borderColor} isNumeric>
                      {fw.requiredTotal}
                    </Td>
                    <Td borderColor={borderColor} isNumeric>
                      <Text color="green.500" fontWeight="500">
                        {fw.requiredCovered}
                      </Text>
                    </Td>
                    <Td borderColor={borderColor} isNumeric>
                      <Text color={fw.gapCount > 0 ? 'orange.500' : 'gray.500'} fontWeight="500">
                        {fw.gapCount}
                      </Text>
                    </Td>
                    <Td borderColor={borderColor}>
                      <HStack spacing="4px">
                        <Icon
                          as={fw.gapCount === 0 ? MdCheckCircle : MdWarning}
                          color={fw.gapCount === 0 ? 'green.500' : 'orange.500'}
                          boxSize="14px"
                        />
                        <Text fontSize="xs" color="gray.500">
                          {fw.gapCount === 0 ? 'Compliant' : 'Action Required'}
                        </Text>
                      </HStack>
                    </Td>
                  </Tr>
                );
              })}
            </Tbody>
          </Table>
        </Box>

        {/* Key Findings */}
        <Box mb="16px">
          <Text fontSize="md" fontWeight="600" color={textColor} mb="12px">
            Key Findings
          </Text>
          <VStack align="stretch" spacing="8px">
            {totalGaps === 0 ? (
              <HStack p="12px" bg="green.50" borderRadius="md" spacing="8px">
                <Icon as={MdCheckCircle} color="green.500" />
                <Text fontSize="sm" color="green.700">
                  All required compliance controls are met across all tracked frameworks.
                </Text>
              </HStack>
            ) : (
              <>
                <HStack p="12px" bg="orange.50" borderRadius="md" spacing="8px">
                  <Icon as={MdWarning} color="orange.500" />
                  <Text fontSize="sm" color="orange.700">
                    {totalGaps} compliance gap{totalGaps > 1 ? 's' : ''} identified requiring remediation.
                  </Text>
                </HStack>
                {frameworks
                  .filter((f) => f.gapCount > 0)
                  .slice(0, 3)
                  .map((fw) => (
                    <Text key={fw.id} fontSize="sm" color="gray.600" pl="32px">
                      • {fw.name}: {fw.gapCount} gap{fw.gapCount > 1 ? 's' : ''} in required controls
                    </Text>
                  ))}
              </>
            )}
          </VStack>
        </Box>

        {/* Footer */}
        <Divider mb="16px" />
        <Text fontSize="xs" color="gray.400" textAlign="center">
          This report was generated by Zentinelle AI Governance Platform.
          For detailed remediation steps, view the Gap Analysis section.
        </Text>
      </Box>
    </Box>
  );
}
