#!/usr/bin/env python3
# Usage: python3 scripts/kf.py [docs|list|check]
"""
kf — Zentinelle Knowledge Framework CLI

Commands:
  kf docs     Regenerate BOOTSTRAP-PRIMER sections in all primer target files
  kf list     List all registered knowledge files
  kf check    Verify all registered files exist

Usage:
  python scripts/kf.py docs
  python scripts/kf.py list
  python scripts/kf.py check
"""

import re
import sys
from pathlib import Path

import yaml

REPO_ROOT = Path(__file__).parent.parent
REGISTRY_PATH = REPO_ROOT / "docs" / "registry.yaml"

MARKER_BEGIN = "<!-- BEGIN {section} -->"
MARKER_END = "<!-- END {section} -->"
GENERATED_NOTE = "<!-- Generated by `python scripts/kf.py docs` — do not edit this section manually -->"


def load_registry() -> dict:
    with open(REGISTRY_PATH) as f:
        return yaml.safe_load(f)


def build_primer_table(knowledge_files: list, agent_filter: list[str]) -> str:
    """Build the knowledge system markdown table for a given set of agent names."""
    rows = [
        f for f in knowledge_files
        if not f.get("internal") and any(a in f.get("agents", []) for a in agent_filter)
    ]
    if not rows:
        return ""

    lines = [
        "## Knowledge System",
        "",
        "| File | Role | Read When |",
        "|------|------|-----------|",
    ]
    for f in rows:
        path = f["path"]
        role = f["role"]
        read_when = f["read_when"]
        lines.append(f"| `{path}` | {role} | {read_when} |")

    return "\n".join(lines)


def regenerate_section(file_path: Path, section: str, content: str) -> bool:
    """
    Replace the content between BEGIN/END markers in a file.
    Returns True if the file was modified, False if unchanged.
    """
    begin_marker = MARKER_BEGIN.format(section=section)
    end_marker = MARKER_END.format(section=section)

    text = file_path.read_text()

    pattern = re.compile(
        re.escape(begin_marker) + r".*?" + re.escape(end_marker),
        re.DOTALL,
    )

    replacement = f"{begin_marker}\n{GENERATED_NOTE}\n\n{content}\n\n{end_marker}"

    if not pattern.search(text):
        print(f"  WARNING: markers not found in {file_path.name} — skipping")
        return False

    new_text = pattern.sub(replacement, text)
    if new_text == text:
        print(f"  {file_path.name}: up to date")
        return False

    file_path.write_text(new_text)
    print(f"  {file_path.name}: updated")
    return True


def cmd_docs() -> None:
    """Regenerate BOOTSTRAP-PRIMER sections in all primer target files."""
    registry = load_registry()
    knowledge_files = registry.get("knowledge_files", [])
    primer_targets = registry.get("primer_targets", [])

    print("Regenerating primers...")
    for target in primer_targets:
        file_path = REPO_ROOT / target["file"]
        section = target["section"]
        agents = target["agents"]

        if not file_path.exists():
            print(f"  WARNING: {target['file']} not found — skipping")
            continue

        content = build_primer_table(knowledge_files, agents)
        regenerate_section(file_path, section, content)

    print("Done.")


def cmd_list() -> None:
    """List all registered knowledge files."""
    registry = load_registry()
    files = registry.get("knowledge_files", [])

    print(f"Knowledge files ({len(files)} registered):\n")
    for f in files:
        internal = " [internal]" if f.get("internal") else ""
        exists = "✓" if (REPO_ROOT / f["path"]).exists() else "✗ MISSING"
        agents = ", ".join(f.get("agents", []))
        print(f"  {exists}  {f['path']}{internal}")
        print(f"       Role: {f['role']}")
        print(f"       Agents: {agents}")
        print()

    skills = registry.get("skills", [])
    if skills:
        print(f"Skills ({len(skills)} registered):\n")
        for s in skills:
            exists = "✓" if (REPO_ROOT / s["path"]).exists() else "✗ MISSING"
            print(f"  {exists}  {s['path']}")
            print(f"       Use when: {s['use_when']}")
            print()


def cmd_check() -> None:
    """Verify all registered files exist."""
    registry = load_registry()
    all_files = registry.get("knowledge_files", []) + registry.get("skills", [])

    missing = []
    for f in all_files:
        path = REPO_ROOT / f["path"]
        if not path.exists() and not f.get("internal"):
            missing.append(f["path"])

    if missing:
        print(f"MISSING ({len(missing)} files):")
        for p in missing:
            print(f"  ✗  {p}")
        sys.exit(1)
    else:
        print(f"All {len(all_files)} registered files present. ✓")


COMMANDS = {
    "docs": cmd_docs,
    "list": cmd_list,
    "check": cmd_check,
}


def main() -> None:
    if len(sys.argv) < 2 or sys.argv[1] not in COMMANDS:
        print(__doc__)
        print(f"Available commands: {', '.join(COMMANDS)}")
        sys.exit(1)

    COMMANDS[sys.argv[1]]()


if __name__ == "__main__":
    main()
