"""Create isolated migration ledgers before running per-schema migrations."""
from django.core.management.base import BaseCommand, CommandError
from django.db import connection, transaction


class Command(BaseCommand):
    help = 'Prepare application schemas and independent Django migration ledgers'

    def handle(self, *args, **options):
        with transaction.atomic(), connection.cursor() as cursor:
            cursor.execute('SELECT pg_advisory_xact_lock(%s)', [734661082])
            for schema in ('zentinelle', 'zentinelle_analytics'):
                cursor.execute(f'CREATE SCHEMA IF NOT EXISTS "{schema}"')
                cursor.execute('SELECT to_regclass(%s)', [schema + '.django_migrations'])
                if cursor.fetchone()[0] is not None:
                    continue
                cursor.execute("SELECT tablename FROM pg_tables WHERE schemaname = %s", [schema])
                if cursor.fetchall():
                    raise CommandError(
                        f'{schema} has tables without its own migration ledger. '
                        'Preserve the database and reconcile migration history before upgrading.'
                    )
                # A fallback search_path otherwise discovers the other schema's
                # ledger, reports "No migrations to apply", and creates no analytics tables.
                cursor.execute(f'''CREATE TABLE "{schema}".django_migrations (
                    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    app varchar(255) NOT NULL,
                    name varchar(255) NOT NULL,
                    applied timestamptz NOT NULL
                )''')
        self.stdout.write(self.style.SUCCESS('Independent schema migration ledgers are ready'))
